{% set name = "datamodeldict" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/D/DataModelDict/DataModelDict-{{ version }}.tar.gz
  sha256: 65c36954efa17449c69a4d8cb11c9273593ef01428cd77a609ee134eba771550

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - xmltodict

test:
  imports:
    - DataModelDict
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/DataModelDict
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: Provides the Python DataModelDict class for creating, accessing and manipulating JSON/XML data structures.

  description: |
    The DataModelDict class is used for handling data models that have 
    equivalent representations in XML, JSON, and Python. Constructing 
    data models in this way is convenient as it supports compatibility 
    across different software tools, such as different types of databases.
  doc_url: https://github.com/usnistgov/DataModelDict
  dev_url: https://github.com/usnistgov/DataModelDict

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
