{% set name = "datamodeldict" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/D/DataModelDict/DataModelDict-{{ version }}.tar.gz
  sha256: 0da74146c73ca84bbd3d680c3659464b611228bee48012c3860e320ebf3b5919

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - xmltodict

test:
  requires:
    - python {{ python_min }}
  imports:
    - DataModelDict
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/DataModelDict
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: Provides the Python DataModelDict class for creating, accessing and manipulating JSON/XML data structures.

  description: |
    The DataModelDict class is used for handling data models that have 
    equivalent representations in XML, JSON, and Python. Constructing 
    data models in this way is convenient as it supports compatibility 
    across different software tools, such as different types of databases.
  doc_url: https://github.com/usnistgov/DataModelDict
  dev_url: https://github.com/usnistgov/DataModelDict

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
