schema_version: 1

context:
  name: datamodeldict
  version: "0.9.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/D/DataModelDict/${{ name }}-${{ version }}.tar.gz
  sha256: ce22c4dbdedfc95270d858f3fc6ba29e74a0672ecbbb064ff4ddca3c05e2110c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - pip
    - xmltodict

tests:
  - python:
      imports:
        - DataModelDict
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: NIST-Software
  license_file: LICENSE.TXT
  summary: Provides the Python DataModelDict class for creating, accessing and manipulating JSON/XML data structures.
  description: |
    The DataModelDict class is used for handling data models that have
    equivalent representations in XML, JSON, and Python. Constructing
    data models in this way is convenient as it supports compatibility
    across different software tools, such as different types of databases.
  homepage: https://github.com/usnistgov/DataModelDict
  repository: https://github.com/usnistgov/DataModelDict
  documentation: https://github.com/usnistgov/DataModelDict

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
